apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::881278976933:role/UdacityFlaskDeployCBKubectlRole
      username: build  
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::881278976933:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-pwhR0mWWPdy5
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2024-03-09T03:44:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1379"
  uid: b13065de-675d-4d33-9e4c-77ad343c5fad
